site_name: Your Package
site_description: Project documentation
repo_url: https://github.com/squidfunk/mkdocs-material
repo_name: squidfunk/mkdocs-material
edit_uri: edit/main/docs/

theme:
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default # slate for dark mode
      primary: indigo # color of the top nav bar
      accent: indigo # color of buttons and links
      toggle:
        icon: material/weather-night
        name: Switch to light mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

  name: material
  font:
    text: Roboto
    code: Roboto Mono
  language: en
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
  features:
    - navigation.tabs # enable top navigation tabs
    - navigation.sections # enable section navigation in the sidebar
    - navigation.path # enable breadcrumb navigation
    - navigation.indexes
    - navigation.top # enable "back to top" button
    - navigation.tracking #URL in the address bar is updated with the active anchor as highlighted in the table of contents
    #- navigation.instant # enable instant loading for internal links. You must set site_url when using instant navigation
    - navigation.instant.prefetch # prefetch pages when user hovers over links
    - navigation.instant.progress # progress bar for loading the page
    - navigation.top
    - content.code.copy
    - toc.follow # highlight the current section in the table of contents
    - toc.integrate # integrate the table of contents into the sidebar (right side)
    - search.highlight
    - search.suggest
    - search.share
    - content.action.edit # "Edit on GitHub" link
    - content.action.view


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - footnotes
  - tables
  - pymdownx.inlinehilite
  - toc:
      permalink: true


plugins:
  - search
  - autorefs
  - offline
  - mkdocstrings:
      handlers:
        python:
          options:
              docstring_style: google
              show_source: true
              show_root_heading: true
              show_root_full_path: false

              # Rendering consistency
              heading_level: 2
              separate_signature: true
              show_signature_annotations: true
              signature_crossrefs: true

              # Member rendering controls
              show_members: true
              members_order: source
              filters:
                - "!^_"          # hide private members by default
              inherited_members: false
  - git-revision-date-localized:
      enable_creation_date: true
      type: date
      fallback_to_build_date: true
  # Show git commiters of the code. Requires git-committers plugin installation and Github Token.
  # Alternative: mkdocs-git-authors-plugin
  #- git-committers:
  #    repository: squidfunk/mkdocs-material
  #    branch: main
  - redirects:
      redirect_maps: { }
  - minify:
      minify_html: true

nav:
  - Home: index.md
  - Guides:
      - Getting started: guides/getting_started.md
  - Reference:
      - Overview: reference/index.md
      - my-package: reference/my-package.md

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn
