blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://github.com/barto-official/python-project-template/tree/main/docs
    about: Before opening a new issue, please make sure to read Documentation and CONTRIBUTING.md